### ISSUE TITLE
Failed to build with 0.15.1 and master

### ISSUE THREAD

**Issue by anta40** [jetzig-framework/jetzig#227]
I'm on macOS 15.6.1 (Apple Sillicon) with 2 zigs installed:
```
$ zvm ls
0.15.1
master
```

Make sure the default zig compiler is 0.15.1
`$ zvm use 0.15.1`

Now create a Jetzig project and try to run it
```
$ jetzig init test01
Creating new project in /Users/andretampubolon/Codes/Zig/test01

[create] build.zig ✅
[create] config/database.zig ✅
[create] src/main.zig ✅
[create] src/app/middleware/DemoMiddleware.zig ✅
[create] src/app/views/root.zig ✅
[create] src/app/views/root/index.zmpl ✅
[create] src/app/views/root/_content.zmpl ✅
[create] public/jetzig.png ✅
[create] public/zmpl.png ✅
[create] public/favicon.ico ✅
[create] public/styles.css ✅
[create] .gitignore ✅
(working) . (done)
 ✅ zig fetch --save https://github.com/jetzig-framework/jetzig/archive/b6e0028f46505e0bb9283185ee927ff9c2a3cc49.tar.gz

Setup complete! ✈️ 🦎

Launch your new application:

    $ cd /Users/andretampubolon/Codes/Zig/test01

    $ zig build run or jetzig server

And then browse to http://localhost:8080/

$ cd test01
$ jetzig server
Launching development server. [reload:enabled]
(working) ... (done)
 ❌

[stderr]:
build.zig:10:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("src/main.zig"),
         ^~~~~~~~~~~~~~~~
/Users/andretampubolon/.zvm/0.15.1/lib/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_21153: /Users/andretampubolon/.zvm/0.15.1/lib/std/Build.zig:2215:44
    main: /Users/andretampubolon/.zvm/0.15.1/lib/compiler/build_runner.zig:366:29
    4 reference(s) hidden; use '-freference-trace=6' to see all references

Build failed, waiting for file change...
```

The same error applies after I switch to master and try to build another new project.

**Comment by Cohors1316** [comment]
zig-0.15 is a work in progress. Still working on writergate changes, about half of the framework is currently up to the writergate part 2 commit. There is a tagged 0.14 commit in the short term, but it's my goal to have everything up to at least writergate part 1 as soon as possible.

**Comment by hirenchauhan2** [comment]
Which version does it work with currently?

**Comment by Cohors1316** [comment]
Zig 0.14.1 works with the zig-0.14.1 branch, and there's a tag pointing to the same commit but can't remember exactly what it is off the top of my head. If you run into issues I can add 0.14 to the nix flake.

**Comment by hirenchauhan2** [comment]
I tried with branch `zig-0.14.1` and built the cli and with that init the project and still having issues.

**Comment by Cohors1316** [comment]
What platform are you on?

**Comment by Cohors1316** [comment]
Hmm, I'll boot the windows pc and give it a try. I've had really odd errors with wsl before. Ubuntu?

**Comment by hirenchauhan2** [comment]
Yes I'm using Ubuntu in the WSL.

**Comment by mutantkeyboard** [comment]
The issue is also on the Mac - I tried both Intel based and my M3 machine running macOS Sequoia 15.6.1 . Seems like something has been broken related to build system on 0.15.x branch.

**Comment by Cohors1316** [comment]
@hirenchauhan2 will it build with the v0.14.1 tag?
`git clone --depth 1 --branch v0.14.1 https://github.com/jetzig-framework/jetzig`

**Comment by Jonatanc05** [comment]
Yeah no success on Ubuntu WSL
- `cd ~/`
- `git clone --depth 1 --branch v0.14.1 https://github.com/jetzig-framework/jetzig`
- `cd jetzig/cli`
- `zig build install`
- `cd ~/my-app`
-  `~/jetzig/cli/zig-out/bin/jetzig init` (confirms defaults)
- `zig build run`:

```
zig-0.14.1/lib/std/Build.zig:498:25: error: option 'openssl_lib_name' has unsupported type: *const [3:0]u8
                else => @compileError("option '" ++ field.name ++ "' has unsupported type: " ++ @typeName(T)),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Cohors1316** [comment]
Closing this for now. Jetzig should now be working for zig 0.15.x. If anyone finds something broken then please file a new issue.
