### ISSUE TITLE
Failed to build with 0.15.1 and 0.15.2

### ISSUE THREAD

**Issue by wisonlau** [jetzig-framework/jetzig#238]
I'm on macOS 13.7.6 with 2 zigs installed:

```
$ zvm ls
0.15.1
0.15.2
```

Make sure the default zig compiler is 0.15.1

```
$ zvm use 0.15.1
```

Now create a Jetzig project and try to run it

```
$ jetzig init test01
Creating new project in /Users/heysir/wwwroot/yi/zig/jetzig/study/test01

[create] build.zig ✅
[create] config/database.zig ✅
[create] src/main.zig ✅
[create] src/app/middleware/DemoMiddleware.zig ✅
[create] src/app/views/root.zig ✅
[create] src/app/views/root/index.zmpl ✅
[create] src/app/views/root/_content.zmpl ✅
[create] public/jetzig.png ✅
[create] public/zmpl.png ✅
[create] public/favicon.ico ✅
[create] public/styles.css ✅
[create] .gitignore ✅
(working) . (done)
 ✅ zig fetch --save https://github.com/jetzig-framework/jetzig/archive/5c33b6b5218a53507467ae0647d977f0f659b510.tar.gz

Setup complete! ✈️ 🦎

Launch your new application:

    $ cd /Users/heysir/wwwroot/yi/zig/jetzig/study/test01

    $ zig build run or jetzig server

And then browse to http://localhost:8080/

$ cd test01

$ jetzig server
Launching development server. [reload:enabled]
(working) ... (done)
 ❌

[stderr]:
build.zig:10:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("src/main.zig"),
         ^~~~~~~~~~~~~~~~
/Users/heysir/.zvm/0.15.1/lib/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_20539: /Users/heysir/.zvm/0.15.1/lib/std/Build.zig:2215:44
    main: /Users/heysir/.zvm/0.15.1/lib/compiler/build_runner.zig:366:29
    4 reference(s) hidden; use '-freference-trace=6' to see all references

Build failed, waiting for file change...
```

**Comment by Cohors1316** [comment]
Try the zig-0.15 branch. I just pushed updates to it today so it should work.

**Comment by wisonlau** [comment]
> Try the zig-0.15 branch. I just pushed updates to it today so it should work.

Zig-0.15 branch can run.

```
$ jetzig server
Launching development server. [reload:enabled]
(working) ... (done)
 ✅ zig build -Denvironment=development -Djetzig_runner=true -Ddebug_console=true install --color on
[startup:WARN] Running in development mode, using default development cookie encryption key: `jetzig-development-cookie-secret`
[startup:WARN] Run `jetzig generate secret` and set `JETZIG_SECRET` to remove this warning.
[startup:INFO] Using `postgresql` database adapter with database: `jetzig_demo_dev`.
INFO  [2026-02-29T13:01:34] [worker-0] Job worker started.
INFO  [2026-02-29T13:01:34] [worker-1] Job worker started.
INFO  [2026-02-29T13:01:34] [worker-2] Job worker started.
INFO  [2026-02-29T13:01:34] Listening on http://127.0.0.1:8080 [development] [workers:4 threads:8]
INFO  [2026-02-29T13:01:34] [worker-3] Job worker started.
INFO  [2026-02-29T13:01:37] [611.327ms/GET/200 OK] /
INFO  [2026-02-29T13:01:37] [685us/GET/200 OK] /prism.css
INFO  [2026-02-29T13:01:37] [368us/GET/200 OK] /zmpl.png
INFO  [2026-02-29T13:01:37] [1.739ms/GET/200 OK] /jetzig.png
INFO  [2026-02-29T13:01:37] [382us/GET/200 OK] /prism.js
DEBUG [2026-02-29T13:01:39] [middleware-htmx] HX-Request header, disabling layout.
INFO  [2026-02-29T13:01:39] [3.916ms/GET/200 OK] /quotes/init
INFO  [2026-02-29T13:01:39] [713us/GET/200 OK] /favicon.ico
```
